[package]
name = "integrator-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
dunce.workspace = true
integrator-core = { path = "../integrator-core" }
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
which.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
